okta:
  oauth2:
    issuer: https://dev-359998.okta.com/oauth2/default
    client-id: 0oa1c61c7tWrnzg0H357
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:X4MMgvzCENsab3uA@kma-schedule-ecnbb.gcp.mongodb.net/kma-schedule?retryWrites=true&w=majority
server:
  port: 9000
kma-schedule:
  defaultAuthor: "KMA"
  defaultGroup: "Học viện kỹ thuật Mật mã"
  colors:
    - "red lighten-3"
    - "purple lighten-3"
    - "deep-purple lighten-3"
    - "indigo lighten-3"
    - "blue lighten-3"
    - "cyan lighten-3"
    - "teal lighten-3"
    - "green lighten-3"
    - "light-green lighten-3"
    - "lime lighten-3"
    - "yellow lighten-3"
    - "amber lighten-3"
    - "orange lighten-3"
    - "deep-orange lighten-3"
    - "brown lighten-3"
    - "blue-grey lighten-3"
wit:
  accessToken: "B7N4WMHEEFIDDGKIL6ODPDKT2JGOBTSP"
#logging:
#  level:
#    org.springframework.security: DEBUG